// packages/react/src/VideoEditor.tsx
import {
  useEffect,
  useImperativeHandle,
  useRef,
  useState,
  type CSSProperties,
  type ReactNode,
  type Ref,
} from "react";
import { createPortal } from "react-dom";
import {
  Editor,
  type AspectRatio,
  type EditorApi,
  type Locale,
  type Ms,
  type PlaybackEngineFactory,
  type PreviewLayout,
  type Project,
  type Theme,
} from "@aicut/core";

export type VideoEditorApi = EditorApi;

export interface VideoEditorProps {
  /**
   * Initial project. Read once on mount — to swap projects after mount,
   * call `apiRef.current.setProject(...)` so React doesn't reinstantiate
   * the editor and lose playback state.
   */
  defaultProject?: Project;
  /** CSS variable overrides applied on mount and whenever this ref changes. */
  theme?: Theme;
  /**
   * UI string overrides (English default). Mirror prop — switching the
   * value calls `editor.setLocale` and the toolbar / canvas labels
   * update in place. Use `localeZh` from `@aicut/core` for Chinese.
   */
  locale?: Partial<Locale>;

  className?: string;
  style?: CSSProperties;

  /** Imperative handle for cut/seek/getProject/setProject/etc. */
  apiRef?: Ref<VideoEditorApi | null>;

  onReady?: (api: VideoEditorApi) => void;
  onChange?: (project: Project) => void;
  onExport?: (project: Project) => void;
  onTimeUpdate?: (timeMs: Ms) => void;
  onPlay?: () => void;
  onPause?: () => void;
  onSelectionChange?: (clipId: string | null) => void;
  onError?: (error: Error) => void;

  /**
   * Rendered into the very left of the editor's top toolbar — host
   * adds anything here (size dropdown, branding, status badge). The
   * library reserves no space for it; if you pass nothing, no
   * separator appears.
   */
  toolbarLeft?: ReactNode;
  /** Same as `toolbarLeft` but at the very right of the toolbar. */
  toolbarRight?: ReactNode;
  /**
   * Rendered into the LEFT side of an optional header bar above the
   * preview (project name, file menu, breadcrumbs). The header
   * collapses entirely when both header slots are empty, so the
   * default layout is identical to before this slot existed.
   */
  headerLeft?: ReactNode;
  /** Right side of the editor header — conventionally Share / Export / profile. */
  headerRight?: ReactNode;
  /**
   * Picks how the preview area sits in the row below the header.
   * - `"fullWidth"` (default): preview spans the entire row — same as
   *   today's chrome.
   * - `"centered"`: preview pins to the middle third (CapCut-desktop
   *   style), with `panelLeft` / `panelRight` slots flanking it.
   *
   * Reactive — swap any time without remount.
   */
  previewLayout?: PreviewLayout;
  /**
   * Rendered into the left column of the main row when
   * `previewLayout === "centered"`. The library reserves the column
   * box; if you pass nothing it stays empty. In `fullWidth` layout
   * the slot is hidden via CSS so the preview occupies the full row.
   */
  panelLeft?: ReactNode;
  /** Right-of-preview column slot — mirror of `panelLeft`. */
  panelRight?: ReactNode;

  /**
   * Initial-only — picks the playback engine used by the underlying
   * core Editor. Defaults to the built-in `HtmlVideoEngine`. Pass a
   * factory to plug in a custom engine (WebCodecs, WebGL compositor,
   * IPC bridge to a native player, …). Swapping this prop after mount
   * has no effect — the editor binds its engine at construction.
   */
  playbackEngine?: PlaybackEngineFactory;
  /**
   * Initial-only — pixel height of each track row (default 56). Lower
   * values (~32–40) shrink the timeline for small viewports where the
   * default crowds out the preview. Applied process-wide; to re-apply
   * change this prop AND remount the component (e.g. via `key`).
   */
  trackHeight?: number;
  /** Initial-only — pixel height of the timeline ruler (default 24). */
  rulerHeight?: number;
  /**
   * Pixel height of the whole bottom timeline area (default 240).
   * Reactive — set anytime to change. The canvas inside fills 100%
   * and shows an internal scrollbar when track count overflows.
   * Useful range: [120, 480] depending on viewport.
   */
  timelineHeight?: number;
  /**
   * Minimum pixel gap between timeline ruler major ticks. The library
   * picks the "nicest" interval (1s, 0.5s, 0.2s, …) that keeps majors
   * at least this far apart for the current zoom. Default 80; lower
   * (~50) packs labels denser, higher (~140) spaces them out.
   * Reactive — change anytime to retune density without remount.
   */
  rulerMinTickPx?: number;
  /**
   * Per-clip keyframe animation (X / Y / Scale). Reactive — set
   * `{ enabled: true }` to surface keyframe diamonds on the timeline
   * and route the canvas-based engines through the transform pipeline.
   * Disabling hides the editing UI but preserves the data in
   * `Project.tracks[].clips[].keyframes`.
   *
   * `HtmlVideoEngine` cannot animate frames; swap to
   * `CanvasCompositorEngine` or `WebCodecsEngine` for live preview.
   */
  keyframes?: { enabled?: boolean };
  /** Fires when the user selects or deselects a keyframe diamond. */
  onKeyframeSelectionChange?: (
    target: { clipId: string; keyframeId: string } | null,
  ) => void;
  /**
   * Jump-to-clip-edge toolbar cluster (|◀ ▶|) + I/O keyboard shortcuts.
   * Reactive — set `{ enabled: true }` to surface the buttons next to
   * the keyframe diamond and bind the shortcuts. Off hides the buttons
   * entirely (display: none, no toolbar space cost) and lets I/O
   * fall through to the page.
   */
  clipEdgeNav?: { enabled?: boolean };
  /**
   * Multi-track picture-in-picture compositing in the preview. Off
   * by default (today's single-clip behaviour). Reactive — flip
   * `enabled: true` to make every video track's currently-active
   * clip paint at the playhead, with track `0` on top.
   *
   * Audio policy: only the top track's clip stays unmuted; lower
   * tracks mute. Same-source caveat: a single decoder per source
   * means a clip on two tracks plays from one currentTime only —
   * upload the file twice for separate ids if you need both ends
   * playing independently.
   *
   * `toolbarAdd: true` surfaces a built-in "+ PiP overlay" icon
   * button next to the keyframe affordance. Clicking it fires
   * `onPictureInPictureAddRequested` — the LIBRARY doesn't run an
   * upload itself; the host wires up its own file picker / upload
   * pipeline and inserts the resulting clip wherever fits.
   */
  pictureInPicture?: {
    enabled?: boolean;
    toolbarAdd?: boolean;
  };
  /** Fires when the user clicks the built-in "+ PiP overlay"
   *  toolbar button (only present when `pictureInPicture.toolbarAdd`
   *  is true). Host should open a file picker, upload, and create
   *  a new clip on an overlay track. */
  onPictureInPictureAddRequested?: () => void;
  /**
   * Dashed outline of the output canvas on top of the preview.
   * Defaults to `{ enabled: true }` — the frame is purely visual
   * (visualises the current aspect ratio / output dimensions) and is
   * useful even without keyframe editing. Set `{ enabled: false }`
   * for a clean preview. Independent of `keyframes`: when keyframes
   * mode is on, the frame body additionally becomes draggable (pan)
   * and grows corner scale handles.
   */
  previewFrame?: { enabled?: boolean };
  /**
   * Built-in aspect-ratio picker (CapCut-style 比例 dropdown). Reactive
   * — set `{ enabled: true }` to surface the chip at the left of the
   * toolbar. Off keeps today's chrome unchanged. Pair with
   * `onAspectChange` to drive the host's preview letterbox / export
   * defaults; the library does not letterbox by itself.
   */
  aspect?: { enabled?: boolean };
  /** Fires when the user picks an output aspect (or "Original" → null). */
  onAspectChange?: (aspect: AspectRatio | null) => void;
}

/**
 * Declarative React shell over `@aicut/core` `Editor`. Mounts the
 * editor instance once, mirrors prop changes (`theme`) into it, and
 * forwards events as React-style callbacks.
 *
 * Intentionally uncontrolled for project state — the editor owns the
 * current project. Use `onChange` to persist and `apiRef.setProject`
 * to restore.
 */
export function VideoEditor(props: VideoEditorProps) {
  const hostRef = useRef<HTMLDivElement | null>(null);
  const editorRef = useRef<Editor | null>(null);
  // Toolbar slot DOM nodes don't exist until the editor mounts; we
  // hold them in state so React re-runs the render after mount and
  // the portals attach. Tracked separately for left + right because
  // each is independently controlled by host props.
  const [slots, setSlots] = useState<{
    left: HTMLElement;
    right: HTMLElement;
    headerLeft: HTMLElement;
    headerRight: HTMLElement;
    panelLeft: HTMLElement;
    panelRight: HTMLElement;
  } | null>(null);

  // Latest-callback refs so the effect that creates the editor doesn't
  // re-run on every parent render just because props.onChange is a new
  // identity — the editor would otherwise be torn down constantly.
  const cbRef = useRef(props);
  cbRef.current = props;

  useEffect(() => {
    const host = hostRef.current;
    if (!host) return;
    const editor = Editor.create({
      container: host,
      project: cbRef.current.defaultProject,
      theme: cbRef.current.theme,
      locale: cbRef.current.locale,
      playbackEngine: cbRef.current.playbackEngine,
      ...(cbRef.current.trackHeight != null
        ? { trackHeight: cbRef.current.trackHeight }
        : {}),
      ...(cbRef.current.rulerHeight != null
        ? { rulerHeight: cbRef.current.rulerHeight }
        : {}),
      ...(cbRef.current.timelineHeight != null
        ? { timelineHeight: cbRef.current.timelineHeight }
        : {}),
      ...(cbRef.current.keyframes != null
        ? { keyframes: cbRef.current.keyframes }
        : {}),
      ...(cbRef.current.clipEdgeNav != null
        ? { clipEdgeNav: cbRef.current.clipEdgeNav }
        : {}),
      ...(cbRef.current.previewFrame != null
        ? { previewFrame: cbRef.current.previewFrame }
        : {}),
      ...(cbRef.current.pictureInPicture != null
        ? { pictureInPicture: cbRef.current.pictureInPicture }
        : {}),
      ...(cbRef.current.aspect != null
        ? { aspect: cbRef.current.aspect }
        : {}),
      ...(cbRef.current.previewLayout != null
        ? { previewLayout: cbRef.current.previewLayout }
        : {}),
      ...(cbRef.current.rulerMinTickPx != null
        ? { rulerMinTickPx: cbRef.current.rulerMinTickPx }
        : {}),
    });
    editorRef.current = editor;
    setSlots({
      left: editor.toolbarLeft,
      right: editor.toolbarRight,
      headerLeft: editor.headerLeft,
      headerRight: editor.headerRight,
      panelLeft: editor.panelLeft,
      panelRight: editor.panelRight,
    });

    const offs = [
      editor.on("change", ({ project }) => cbRef.current.onChange?.(project)),
      editor.on("export", ({ project }) => cbRef.current.onExport?.(project)),
      editor.on("time", ({ timeMs }) => cbRef.current.onTimeUpdate?.(timeMs)),
      editor.on("play", () => cbRef.current.onPlay?.()),
      editor.on("pause", () => cbRef.current.onPause?.()),
      editor.on("selectionChange", ({ clipId }) =>
        cbRef.current.onSelectionChange?.(clipId),
      ),
      editor.on("keyframeSelectionChange", ({ target }) =>
        cbRef.current.onKeyframeSelectionChange?.(target),
      ),
      editor.on("aspectChange", ({ aspect }) =>
        cbRef.current.onAspectChange?.(aspect),
      ),
      editor.on("requestPictureInPictureAdd", () =>
        cbRef.current.onPictureInPictureAddRequested?.(),
      ),
      editor.on("error", ({ error }) => cbRef.current.onError?.(error)),
    ];

    cbRef.current.onReady?.(editor);

    return () => {
      for (const off of offs) off();
      editor.destroy();
      editorRef.current = null;
      setSlots(null);
    };
    // Editor lifecycle is tied to mount; we deliberately don't list
    // any reactive deps. `theme` changes are pushed through the
    // separate effect below.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    if (props.theme) editorRef.current?.setTheme(props.theme);
  }, [props.theme]);

  useEffect(() => {
    if (props.locale) editorRef.current?.setLocale(props.locale);
  }, [props.locale]);

  // Reactive — flipping `keyframes.enabled` instantly toggles diamond
  // visibility on the timeline and routes the canvas / WebCodecs
  // engines through the transform pipeline (or not). Data is
  // preserved either way.
  useEffect(() => {
    const editor = editorRef.current;
    if (!editor) return;
    const desired = props.keyframes?.enabled === true;
    if (editor.isKeyframesEnabled() !== desired) {
      editor.setKeyframesEnabled(desired);
    }
  }, [props.keyframes?.enabled]);

  useEffect(() => {
    const editor = editorRef.current;
    if (!editor) return;
    const desired = props.clipEdgeNav?.enabled === true;
    if (editor.isClipEdgeNavEnabled() !== desired) {
      editor.setClipEdgeNavEnabled(desired);
    }
  }, [props.clipEdgeNav?.enabled]);

  useEffect(() => {
    const editor = editorRef.current;
    if (!editor) return;
    // Default true — only flip when host explicitly sets false.
    const desired = props.previewFrame?.enabled !== false;
    if (editor.isPreviewFrameEnabled() !== desired) {
      editor.setPreviewFrameEnabled(desired);
    }
  }, [props.previewFrame?.enabled]);

  useEffect(() => {
    const editor = editorRef.current;
    if (!editor) return;
    const desired = props.pictureInPicture?.enabled === true;
    if (editor.isPictureInPictureEnabled() !== desired) {
      editor.setPictureInPictureEnabled(desired);
    }
  }, [props.pictureInPicture?.enabled]);

  useEffect(() => {
    const editor = editorRef.current;
    if (!editor) return;
    const desired = props.aspect?.enabled === true;
    if (editor.isAspectEnabled() !== desired) {
      editor.setAspectEnabled(desired);
    }
  }, [props.aspect?.enabled]);

  useEffect(() => {
    const editor = editorRef.current;
    if (!editor) return;
    if (props.previewLayout == null) return;
    if (editor.getPreviewLayout() !== props.previewLayout) {
      editor.setPreviewLayout(props.previewLayout);
    }
  }, [props.previewLayout]);

  useEffect(() => {
    const editor = editorRef.current;
    if (!editor) return;
    if (props.rulerMinTickPx == null) return;
    if (editor.getRulerMinTickPx() !== props.rulerMinTickPx) {
      editor.setRulerMinTickPx(props.rulerMinTickPx);
    }
  }, [props.rulerMinTickPx]);

  // Reactive — the underlying CSS custom property can be updated on
  // the container any time; the timeline picks up the new height
  // immediately via CSS. No remount required.
  useEffect(() => {
    const host = hostRef.current;
    if (!host) return;
    if (props.timelineHeight != null && props.timelineHeight > 0) {
      host.style.setProperty(
        "--aicut-timeline-height",
        `${Math.round(props.timelineHeight)}px`,
      );
    } else {
      host.style.removeProperty("--aicut-timeline-height");
    }
  }, [props.timelineHeight]);

  // Deps must include `slots`. Without it, the factory ran once during
  // the first commit — BEFORE the useEffect above had a chance to
  // create the editor — so `apiRef.current` was permanently locked to
  // null. `slots` flips from null to a real value the same instant
  // the editor is created, so it's the cleanest re-run trigger.
  useImperativeHandle<VideoEditorApi | null, VideoEditorApi | null>(
    props.apiRef,
    () => editorRef.current,
    [slots],
  );

  return (
    <div
      ref={hostRef}
      className={props.className}
      style={props.style}
      data-aicut-host=""
    >
      {slots && props.toolbarLeft != null
        ? createPortal(props.toolbarLeft, slots.left)
        : null}
      {slots && props.toolbarRight != null
        ? createPortal(props.toolbarRight, slots.right)
        : null}
      {slots && props.headerLeft != null
        ? createPortal(props.headerLeft, slots.headerLeft)
        : null}
      {slots && props.headerRight != null
        ? createPortal(props.headerRight, slots.headerRight)
        : null}
      {slots && props.panelLeft != null
        ? createPortal(props.panelLeft, slots.panelLeft)
        : null}
      {slots && props.panelRight != null
        ? createPortal(props.panelRight, slots.panelRight)
        : null}
    </div>
  );
}

// packages/vue/src/VideoEditor.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, watch } from "vue";
import {
  Editor,
  type AspectRatio,
  type EditorApi,
  type Locale,
  type Ms,
  type PlaybackEngineFactory,
  type PreviewLayout,
  type Project,
  type Theme,
} from "@aicut/core";

/**
 * Vue 3 wrapper around `@aicut/core`. Same shape as `@aicut/react`:
 * uncontrolled for project state, theme is reactive, API exposed via
 * `defineExpose` so a parent `ref` can call cut/seek/setProject/etc.
 */
const props = defineProps<{
  defaultProject?: Project;
  theme?: Theme;
  /** UI string overrides (English default). Reactive — swap to `localeZh` for Chinese. */
  locale?: Partial<Locale>;
  /**
   * Initial-only factory for a custom playback engine. Defaults to the
   * built-in `HtmlVideoEngine`. Pass `WebCodecsEngine` (v0.6+) or your
   * own engine to override. Bound at mount; later prop changes are
   * ignored.
   */
  playbackEngine?: PlaybackEngineFactory;
  /**
   * Initial-only — pixel height of each track row (default 56). Lower
   * values (~32–40) shrink the timeline for small viewports. Applied
   * process-wide at construction time.
   */
  trackHeight?: number;
  /** Initial-only — pixel height of the timeline ruler (default 24). */
  rulerHeight?: number;
  /**
   * Pixel height of the whole bottom timeline area (default 240).
   * Reactive — swap any time to recompact. The canvas inside fills
   * 100% and shows an internal scrollbar when track count overflows.
   */
  timelineHeight?: number;
  /**
   * Per-clip keyframe animation (X / Y / Scale). Reactive — set
   * `{ enabled: true }` to surface keyframe diamonds on the timeline
   * and route the canvas-based engines through the transform pipeline.
   * Data is preserved when disabled.
   */
  keyframes?: { enabled?: boolean };
  /**
   * Jump-to-clip-edge toolbar cluster (|◀ ▶|) + I/O keyboard shortcuts.
   * Reactive — set `{ enabled: true }` to surface the buttons next to
   * the keyframe diamond and bind the shortcuts. Off hides the buttons
   * entirely (no toolbar space cost).
   */
  clipEdgeNav?: { enabled?: boolean };
  /**
   * Dashed outline of the output canvas on top of the preview.
   * Defaults to `{ enabled: true }` — purely visual. Set
   * `{ enabled: false }` to hide it entirely. Independent of
   * `keyframes`; when keyframes mode is also on the frame body
   * becomes draggable and grows corner scale handles.
   */
  previewFrame?: { enabled?: boolean };
  /**
   * Multi-track picture-in-picture compositing in the preview. Off
   * by default. Reactive — set `{ enabled: true }` to composite
   * every video track's active clip with track `0` on top. Audio
   * policy: only top track unmuted; lower tracks mute.
   */
  pictureInPicture?: { enabled?: boolean; toolbarAdd?: boolean };
  /**
   * Built-in aspect-ratio picker (CapCut-style 比例 dropdown). Reactive
   * — set `{ enabled: true }` to surface the chip at the left of the
   * toolbar. Listen for `aspectChange` to drive your preview letterbox
   * / export defaults.
   */
  aspect?: { enabled?: boolean };
  /**
   * Picks how the preview area sits in the row below the header.
   * `"centered"` (default) pins it to the middle third (CapCut-desktop
   * style) with `panelLeft` / `panelRight` slots flanking it.
   * `"fullWidth"` spans the row with no side columns. Reactive.
   */
  previewLayout?: PreviewLayout;
  /**
   * Minimum pixel gap between timeline ruler major ticks. Default 80;
   * lower (~50) packs labels denser, higher (~140) spaces them out.
   * Reactive — change anytime to retune density.
   */
  rulerMinTickPx?: number;
}>();

const emit = defineEmits<{
  (e: "ready", api: EditorApi): void;
  (e: "change", project: Project): void;
  (e: "export", project: Project): void;
  (e: "timeUpdate", timeMs: Ms): void;
  (e: "play"): void;
  (e: "pause"): void;
  (e: "selectionChange", clipId: string | null): void;
  (
    e: "keyframeSelectionChange",
    target: { clipId: string; keyframeId: string } | null,
  ): void;
  (e: "aspectChange", aspect: AspectRatio | null): void;
  (e: "pictureInPictureAddRequested"): void;
  (e: "error", error: Error): void;
}>();

const host = ref<HTMLDivElement | null>(null);
let editor: Editor | null = null;
const offs: Array<() => void> = [];
/** Header slot DOM nodes — set after editor mount so Vue Teleports
 *  have a valid target. Library renders nothing here; named slots
 *  `#headerLeft` / `#headerRight` portal whatever the host provides. */
const headerLeftSlot = ref<HTMLElement | null>(null);
const headerRightSlot = ref<HTMLElement | null>(null);
/** Side-panel slot DOM nodes — visible only when
 *  `previewLayout === "centered"`. */
const panelLeftSlot = ref<HTMLElement | null>(null);
const panelRightSlot = ref<HTMLElement | null>(null);

onMounted(() => {
  if (!host.value) return;
  editor = Editor.create({
    container: host.value,
    project: props.defaultProject,
    theme: props.theme,
    locale: props.locale,
    playbackEngine: props.playbackEngine,
    ...(props.trackHeight != null ? { trackHeight: props.trackHeight } : {}),
    ...(props.rulerHeight != null ? { rulerHeight: props.rulerHeight } : {}),
    ...(props.timelineHeight != null
      ? { timelineHeight: props.timelineHeight }
      : {}),
    ...(props.keyframes != null ? { keyframes: props.keyframes } : {}),
    ...(props.clipEdgeNav != null ? { clipEdgeNav: props.clipEdgeNav } : {}),
    ...(props.previewFrame != null
      ? { previewFrame: props.previewFrame }
      : {}),
    ...(props.pictureInPicture != null
      ? { pictureInPicture: props.pictureInPicture }
      : {}),
    ...(props.aspect != null ? { aspect: props.aspect } : {}),
    ...(props.previewLayout != null
      ? { previewLayout: props.previewLayout }
      : {}),
    ...(props.rulerMinTickPx != null
      ? { rulerMinTickPx: props.rulerMinTickPx }
      : {}),
  });

  offs.push(
    editor.on("change", ({ project }) => emit("change", project)),
    editor.on("export", ({ project }) => emit("export", project)),
    editor.on("time", ({ timeMs }) => emit("timeUpdate", timeMs)),
    editor.on("play", () => emit("play")),
    editor.on("pause", () => emit("pause")),
    editor.on("selectionChange", ({ clipId }) =>
      emit("selectionChange", clipId),
    ),
    editor.on("keyframeSelectionChange", ({ target }) =>
      emit("keyframeSelectionChange", target),
    ),
    editor.on("aspectChange", ({ aspect }) => emit("aspectChange", aspect)),
    editor.on("requestPictureInPictureAdd", () =>
      emit("pictureInPictureAddRequested"),
    ),
    editor.on("error", ({ error }) => emit("error", error)),
  );

  headerLeftSlot.value = editor.headerLeft;
  headerRightSlot.value = editor.headerRight;
  panelLeftSlot.value = editor.panelLeft;
  panelRightSlot.value = editor.panelRight;
  emit("ready", editor);
});

watch(
  () => props.theme,
  (theme) => {
    if (theme && editor) editor.setTheme(theme);
  },
);

watch(
  () => props.locale,
  (locale) => {
    if (locale && editor) editor.setLocale(locale);
  },
);

// Reactive — flip keyframe mode without remount. Data preserved.
watch(
  () => props.keyframes?.enabled,
  (enabled) => {
    if (!editor) return;
    const desired = enabled === true;
    if (editor.isKeyframesEnabled() !== desired) {
      editor.setKeyframesEnabled(desired);
    }
  },
);

// Reactive — flip clip-edge nav cluster (|◀ ▶|) + I/O shortcuts.
watch(
  () => props.clipEdgeNav?.enabled,
  (enabled) => {
    if (!editor) return;
    const desired = enabled === true;
    if (editor.isClipEdgeNavEnabled() !== desired) {
      editor.setClipEdgeNavEnabled(desired);
    }
  },
);

// Reactive — flip the dashed output-frame outline.
watch(
  () => props.previewFrame?.enabled,
  (enabled) => {
    if (!editor) return;
    const desired = enabled !== false;
    if (editor.isPreviewFrameEnabled() !== desired) {
      editor.setPreviewFrameEnabled(desired);
    }
  },
);

// Reactive — flip multi-track PiP compositing.
watch(
  () => props.pictureInPicture?.enabled,
  (enabled) => {
    if (!editor) return;
    const desired = enabled === true;
    if (editor.isPictureInPictureEnabled() !== desired) {
      editor.setPictureInPictureEnabled(desired);
    }
  },
);

// Reactive — flip built-in aspect picker visibility.
watch(
  () => props.aspect?.enabled,
  (enabled) => {
    if (!editor) return;
    const desired = enabled === true;
    if (editor.isAspectEnabled() !== desired) {
      editor.setAspectEnabled(desired);
    }
  },
);

// Reactive — swap preview layout (fullWidth ↔ centered).
watch(
  () => props.previewLayout,
  (layout) => {
    if (!editor || layout == null) return;
    if (editor.getPreviewLayout() !== layout) {
      editor.setPreviewLayout(layout);
    }
  },
);

watch(
  () => props.rulerMinTickPx,
  (px) => {
    if (!editor || px == null) return;
    if (editor.getRulerMinTickPx() !== px) editor.setRulerMinTickPx(px);
  },
);

// Reactive — sets the CSS custom property directly so the timeline
// height can be tweaked without remounting.
watch(
  () => props.timelineHeight,
  (timelineHeight) => {
    const root = host.value;
    if (!root) return;
    if (timelineHeight != null && timelineHeight > 0) {
      root.style.setProperty(
        "--aicut-timeline-height",
        `${Math.round(timelineHeight)}px`,
      );
    } else {
      root.style.removeProperty("--aicut-timeline-height");
    }
  },
);

onBeforeUnmount(() => {
  for (const off of offs) off();
  offs.length = 0;
  editor?.destroy();
  editor = null;
  headerLeftSlot.value = null;
  headerRightSlot.value = null;
  panelLeftSlot.value = null;
  panelRightSlot.value = null;
});

defineExpose({
  /** Returns the underlying core API or null if not yet mounted. */
  api: (): EditorApi | null => editor,
});
</script>

<template>
  <div ref="host" data-aicut-host="">
    <Teleport v-if="headerLeftSlot" :to="headerLeftSlot">
      <slot name="headerLeft" />
    </Teleport>
    <Teleport v-if="headerRightSlot" :to="headerRightSlot">
      <slot name="headerRight" />
    </Teleport>
    <Teleport v-if="panelLeftSlot" :to="panelLeftSlot">
      <slot name="panelLeft" />
    </Teleport>
    <Teleport v-if="panelRightSlot" :to="panelRightSlot">
      <slot name="panelRight" />
    </Teleport>
  </div>
</template>
